
/*
 * OriginStamp Client
 *
 * OpenAPI spec version: 3.0
 * OriginStamp Documentation: https://docs.originstamp.com
 * Contact: mail@originstamp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.OriginStamp) {
      root.OriginStamp = {};
    }
    root.OriginStamp.CurrencyModel = factory(root.OriginStamp.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The CurrencyModel model module.
   * @module model/CurrencyModel
   * @version 3.0
   */

  /**
   * Constructs a new <code>CurrencyModel</code>.
   * Contains the currency ID and currency name
   * @alias module:model/CurrencyModel
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>CurrencyModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CurrencyModel} obj Optional instance to populate.
   * @return {module:model/CurrencyModel} The populated <code>CurrencyModel</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('currency'))
        obj.currency = ApiClient.convertToType(data['currency'], 'String');
      if (data.hasOwnProperty('currency_id'))
        obj.currencyId = ApiClient.convertToType(data['currency_id'], 'Number');
    }
    return obj;
  }

  /**
   * Name of the currency (uppercase)
   * @member {String} currency
   */
  exports.prototype.currency = undefined;

  /**
   * ID of the currency, e.g. 0: Bitcoin 1: Ethereum
   * @member {Number} currencyId
   */
  exports.prototype.currencyId = undefined;


  return exports;

}));
