
/*
 * OriginStamp Client
 *
 * OpenAPI spec version: 3.0
 * OriginStamp Documentation: https://docs.originstamp.com
 * Contact: mail@originstamp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.OriginStamp) {
      root.OriginStamp = {};
    }
    root.OriginStamp.DownloadLinkResponse = factory(root.OriginStamp.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The DownloadLinkResponse model module.
   * @module model/DownloadLinkResponse
   * @version 3.0
   */

  /**
   * Constructs a new <code>DownloadLinkResponse</code>.
   * DTO for the download link of a proof request.
   * @alias module:model/DownloadLinkResponse
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>DownloadLinkResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DownloadLinkResponse} obj Optional instance to populate.
   * @return {module:model/DownloadLinkResponse} The populated <code>DownloadLinkResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('download_url'))
        obj.downloadUrl = ApiClient.convertToType(data['download_url'], 'String');
      if (data.hasOwnProperty('file_name'))
        obj.fileName = ApiClient.convertToType(data['file_name'], 'String');
      if (data.hasOwnProperty('file_size_bytes'))
        obj.fileSizeBytes = ApiClient.convertToType(data['file_size_bytes'], 'Number');
    }
    return obj;
  }

  /**
   * URL to download file.
   * @member {String} downloadUrl
   */
  exports.prototype.downloadUrl = undefined;

  /**
   * File name of downloaded file.
   * @member {String} fileName
   */
  exports.prototype.fileName = undefined;

  /**
   * File size in bytes.
   * @member {Number} fileSizeBytes
   */
  exports.prototype.fileSizeBytes = undefined;


  return exports;

}));
