
/*
 * OriginStamp Client
 *
 * OpenAPI spec version: 3.0
 * OriginStamp Documentation: https://docs.originstamp.com
 * Contact: mail@originstamp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.OriginStamp) {
      root.OriginStamp = {};
    }
    root.OriginStamp.ManualWebhookRequest = factory(root.OriginStamp.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The ManualWebhookRequest model module.
   * @module model/ManualWebhookRequest
   * @version 3.0
   */

  /**
   * Constructs a new <code>ManualWebhookRequest</code>.
   * Request object for a manual webhook request.
   * @alias module:model/ManualWebhookRequest
   * @class
   * @param hash {String} SHA-256 Hash in Hex representation.
   * @param webhookUrl {String} The target URL to which we send the timestamp information of the requested hash via a post request.
   */
  var exports = function(hash, webhookUrl) {
    this.hash = hash;
    this.webhook_url = webhookUrl;
  };

  /**
   * Constructs a <code>ManualWebhookRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ManualWebhookRequest} obj Optional instance to populate.
   * @return {module:model/ManualWebhookRequest} The populated <code>ManualWebhookRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('hash'))
        obj.hash = ApiClient.convertToType(data['hash'], 'String');
      if (data.hasOwnProperty('webhook_url'))
        obj.webhook_url = ApiClient.convertToType(data['webhook_url'], 'String');
    }
    return obj;
  }

  /**
   * SHA-256 Hash in Hex representation.
   * @member {String} hash
   */
  exports.prototype.hash = undefined;

  /**
   * The target URL to which we send the timestamp information of the requested hash via a post request.
   * @member {String} webhook_url
   */
  exports.prototype.webhook_url = undefined;


  return exports;

}));
