
/*
 * OriginStamp Client
 *
 * OpenAPI spec version: 3.0
 * OriginStamp Documentation: https://docs.originstamp.com
 * Contact: mail@originstamp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/TimestampRequest'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./TimestampRequest'));
  } else {
    // Browser globals (root is window)
    if (!root.OriginStamp) {
      root.OriginStamp = {};
    }
    root.OriginStamp.TimestampBulkRequest = factory(root.OriginStamp.ApiClient, root.OriginStamp.TimestampRequest);
  }
}(this, function(ApiClient, TimestampRequest) {
  'use strict';

  /**
   * The TimestampBulkRequest model module.
   * @module model/TimestampBulkRequest
   * @version 3.0
   */

  /**
   * Constructs a new <code>TimestampBulkRequest</code>.
   * Request object for bulk timestamping request.
   * @alias module:model/TimestampBulkRequest
   * @class
   * @param timestamps {Array.<module:model/TimestampRequest>} Array of timestamp request DTOs which will be timestamped.
   */
  var exports = function(timestamps) {
    this.timestamps = timestamps;
  };

  /**
   * Constructs a <code>TimestampBulkRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TimestampBulkRequest} obj Optional instance to populate.
   * @return {module:model/TimestampBulkRequest} The populated <code>TimestampBulkRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('timestamps'))
        obj.timestamps = ApiClient.convertToType(data['timestamps'], [TimestampRequest]);
    }
    return obj;
  }

  /**
   * Array of timestamp request DTOs which will be timestamped.
   * @member {Array.<module:model/TimestampRequest>} timestamps
   */
  exports.prototype.timestamps = undefined;


  return exports;

}));
