
/*
 * OriginStamp Client
 *
 * OpenAPI spec version: 3.0
 * OriginStamp Documentation: https://docs.originstamp.com
 * Contact: mail@originstamp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.OriginStamp) {
      root.OriginStamp = {};
    }
    root.OriginStamp.UsageResponse = factory(root.OriginStamp.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The UsageResponse model module.
   * @module model/UsageResponse
   * @version 3.0
   */

  /**
   * Constructs a new <code>UsageResponse</code>.
   * Usage metric for this month.
   * @alias module:model/UsageResponse
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>UsageResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UsageResponse} obj Optional instance to populate.
   * @return {module:model/UsageResponse} The populated <code>UsageResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('certificate_per_month'))
        obj.certificate_per_month = ApiClient.convertToType(data['certificate_per_month'], 'Number');
      if (data.hasOwnProperty('consumed_certificates'))
        obj.consumed_certificates = ApiClient.convertToType(data['consumed_certificates'], 'Number');
      if (data.hasOwnProperty('consumed_credits'))
        obj.consumed_credits = ApiClient.convertToType(data['consumed_credits'], 'Number');
      if (data.hasOwnProperty('consumed_timestamps'))
        obj.consumed_timestamps = ApiClient.convertToType(data['consumed_timestamps'], 'Number');
      if (data.hasOwnProperty('credits_per_month'))
        obj.credits_per_month = ApiClient.convertToType(data['credits_per_month'], 'Number');
      if (data.hasOwnProperty('limitation_type'))
        obj.limitation_type = ApiClient.convertToType(data['limitation_type'], 'Number');
      if (data.hasOwnProperty('remaining_credits'))
        obj.remaining_credits = ApiClient.convertToType(data['remaining_credits'], 'Number');
      if (data.hasOwnProperty('timestamps_per_month'))
        obj.timestamps_per_month = ApiClient.convertToType(data['timestamps_per_month'], 'Number');
    }
    return obj;
  }

  /**
   * Total number of certificates available per month.
   * @member {Number} certificate_per_month
   */
  exports.prototype.certificate_per_month = undefined;

  /**
   * Number of certificates requested for the current month.
   * @member {Number} consumed_certificates
   */
  exports.prototype.consumed_certificates = undefined;

  /**
   * Number of used credits for the current month.
   * @member {Number} consumed_credits
   */
  exports.prototype.consumed_credits = undefined;

  /**
   * Number of timestamps created for the current month.
   * @member {Number} consumed_timestamps
   */
  exports.prototype.consumed_timestamps = undefined;

  /**
   * Represents the total number of credits per month.
   * @member {Number} credits_per_month
   */
  exports.prototype.credits_per_month = undefined;

  /**
   * Determines which usage metric is applied (0 = credits, 1 = timestamps).
   * @member {Number} limitation_type
   */
  exports.prototype.limitation_type = undefined;

  /**
   * Remaining number of credits for the current month.
   * @member {Number} remaining_credits
   */
  exports.prototype.remaining_credits = undefined;

  /**
   * Total number of timestamps available per month.
   * @member {Number} timestamps_per_month
   */
  exports.prototype.timestamps_per_month = undefined;


  return exports;

}));
