
/*
 * OriginStamp Client
 *
 * OpenAPI spec version: 3.0
 * OriginStamp Documentation: https://docs.originstamp.com
 * Contact: mail@originstamp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.OriginStamp) {
      root.OriginStamp = {};
    }
    root.OriginStamp.UsageResponse = factory(root.OriginStamp.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The UsageResponse model module.
   * @module model/UsageResponse
   * @version 3.0
   */

  /**
   * Constructs a new <code>UsageResponse</code>.
   * Usage metric for this month.
   * @alias module:model/UsageResponse
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>UsageResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UsageResponse} obj Optional instance to populate.
   * @return {module:model/UsageResponse} The populated <code>UsageResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('certificate_per_month'))
        obj.certificatePerMonth = ApiClient.convertToType(data['certificate_per_month'], 'Number');
      if (data.hasOwnProperty('consumed_certificates'))
        obj.consumedCertificates = ApiClient.convertToType(data['consumed_certificates'], 'Number');
      if (data.hasOwnProperty('consumed_credits'))
        obj.consumedCredits = ApiClient.convertToType(data['consumed_credits'], 'Number');
      if (data.hasOwnProperty('consumed_timestamps'))
        obj.consumedTimestamps = ApiClient.convertToType(data['consumed_timestamps'], 'Number');
      if (data.hasOwnProperty('credits_per_month'))
        obj.creditsPerMonth = ApiClient.convertToType(data['credits_per_month'], 'Number');
      if (data.hasOwnProperty('limitation_type'))
        obj.limitationType = ApiClient.convertToType(data['limitation_type'], 'Number');
      if (data.hasOwnProperty('remaining_credits'))
        obj.remainingCredits = ApiClient.convertToType(data['remaining_credits'], 'Number');
      if (data.hasOwnProperty('timestamps_per_month'))
        obj.timestampsPerMonth = ApiClient.convertToType(data['timestamps_per_month'], 'Number');
    }
    return obj;
  }

  /**
   * Total number of certificates available per month.
   * @member {Number} certificatePerMonth
   */
  exports.prototype.certificatePerMonth = undefined;

  /**
   * Number of certificates requested for the current month.
   * @member {Number} consumedCertificates
   */
  exports.prototype.consumedCertificates = undefined;

  /**
   * Number of used credits for the current month.
   * @member {Number} consumedCredits
   */
  exports.prototype.consumedCredits = undefined;

  /**
   * Number of timestamps created for the current month.
   * @member {Number} consumedTimestamps
   */
  exports.prototype.consumedTimestamps = undefined;

  /**
   * Represents the total number of credits per month.
   * @member {Number} creditsPerMonth
   */
  exports.prototype.creditsPerMonth = undefined;

  /**
   * Determines which usage metric is applied (0 = credits, 1 = timestamps).
   * @member {Number} limitationType
   */
  exports.prototype.limitationType = undefined;

  /**
   * Remaining number of credits for the current month.
   * @member {Number} remainingCredits
   */
  exports.prototype.remainingCredits = undefined;

  /**
   * Total number of timestamps available per month.
   * @member {Number} timestampsPerMonth
   */
  exports.prototype.timestampsPerMonth = undefined;


  return exports;

}));
