
/*
 * OriginStamp Client
 *
 * OpenAPI spec version: 3.0
 * OriginStamp Documentation: https://docs.originstamp.com
 * Contact: mail@originstamp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.OriginStamp) {
      root.OriginStamp = {};
    }
    root.OriginStamp.WebhookResponse = factory(root.OriginStamp.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The WebhookResponse model module.
   * @module model/WebhookResponse
   * @version 3.0
   */

  /**
   * Constructs a new <code>WebhookResponse</code>.
   * response object for a webhook request. Contains only the most recent webhook information for target URL, hash and currency.
   * @alias module:model/WebhookResponse
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>WebhookResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WebhookResponse} obj Optional instance to populate.
   * @return {module:model/WebhookResponse} The populated <code>WebhookResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('currency'))
        obj.currency = ApiClient.convertToType(data['currency'], 'Number');
      if (data.hasOwnProperty('executed'))
        obj.executed = ApiClient.convertToType(data['executed'], 'Boolean');
      if (data.hasOwnProperty('hash'))
        obj.hash = ApiClient.convertToType(data['hash'], 'String');
      if (data.hasOwnProperty('success'))
        obj.success = ApiClient.convertToType(data['success'], 'Boolean');
      if (data.hasOwnProperty('tries'))
        obj.tries = ApiClient.convertToType(data['tries'], 'Number');
    }
    return obj;
  }

  /**
   * Currency for which the webhook is triggered, e.g.  0: Bitcoin 1: Ethereum
   * @member {Number} currency
   */
  exports.prototype.currency = undefined;

  /**
   * Shows if the webhook was executed.
   * @member {Boolean} executed
   */
  exports.prototype.executed = undefined;

  /**
   * The submitted hash in hex representation.
   * @member {String} hash
   */
  exports.prototype.hash = undefined;

  /**
   * Indicates whether the webhook was executed successfully or not.
   * @member {Boolean} success
   */
  exports.prototype.success = undefined;

  /**
   * Returns the number of tries for the webhook execution.
   * @member {Number} tries
   */
  exports.prototype.tries = undefined;


  return exports;

}));
