
/*
 * OriginStamp Client
 *
 * OpenAPI spec version: 3.0
 * OriginStamp Documentation: https://docs.originstamp.com
 * Contact: mail@originstamp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.OriginStamp) {
      root.OriginStamp = {};
    }
    root.OriginStamp.WebhookRequest = factory(root.OriginStamp.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The WebhookRequest model module.
   * @module model/WebhookRequest
   * @version 3.0
   */

  /**
   * Constructs a new <code>WebhookRequest</code>.
   * Request object for a webhook request.
   * @alias module:model/WebhookRequest
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>WebhookRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WebhookRequest} obj Optional instance to populate.
   * @return {module:model/WebhookRequest} The populated <code>WebhookRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('currency'))
        obj.currency = ApiClient.convertToType(data['currency'], 'Number');
      if (data.hasOwnProperty('hash'))
        obj.hash = ApiClient.convertToType(data['hash'], 'String');
      if (data.hasOwnProperty('target'))
        obj.target = ApiClient.convertToType(data['target'], 'String');
    }
    return obj;
  }

  /**
   * Currency ID for which the webhook should be executed. Possible values: 0: Bitcoin 1: Ethereum 2: AION 100: Südkurier
   * @member {Number} currency
   */
  exports.prototype.currency = undefined;

  /**
   * Hash (SHA-256 in HEX) for which a notification is requested.
   * @member {String} hash
   */
  exports.prototype.hash = undefined;

  /**
   * Target address to which a POST request should be executed.
   * @member {String} target
   */
  exports.prototype.target = undefined;


  return exports;

}));
