
/*
 * OriginStamp Client
 *
 * OpenAPI spec version: 3.0
 * OriginStamp Documentation: https://docs.originstamp.com
 * Contact: mail@originstamp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DefaultOfTimestampData', 'model/DefaultOfTimestampResponse', 'model/TimestampBulkRequest'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/DefaultOfTimestampData'), require('../model/DefaultOfTimestampResponse'), require('../model/TimestampBulkRequest'));
  } else {
    // Browser globals (root is window)
    if (!root.OriginStamp) {
      root.OriginStamp = {};
    }
    root.OriginStamp.BulkApi = factory(root.OriginStamp.ApiClient, root.OriginStamp.DefaultOfTimestampData, root.OriginStamp.DefaultOfTimestampResponse, root.OriginStamp.TimestampBulkRequest);
  }
}(this, function(ApiClient, DefaultOfTimestampData, DefaultOfTimestampResponse, TimestampBulkRequest) {
  'use strict';

  /**
   * Bulk service.
   * @module api/BulkApi
   * @version 3.0
   */

  /**
   * Constructs a new BulkApi. 
   * @alias module:api/BulkApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the createBulkTimestamp operation.
     * @callback module:api/BulkApi~createBulkTimestampCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/DefaultOfTimestampResponse>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Bulk Submission
     * With this interface you can submit multiple hashes at once. If your API key is valid, your hashes are added to seeds and scheduled for timestamping. You are also able to submit additional information with every hash, such as a comment or notification target. If the hash already exists, the 'created' field in the response is set to 'false' and the notification(s) of the corresponding hash will be ignored. To later query the status of any hash for a certain blockchain you can use the 'seed_id' field of its inner timestamp structure. This field can be used to query the timestamping status of the selected seed. This is recommended if a large number of hashes were transmitted in a certain time frame. Once a hash is successfully created for a certain crypto currency, we can notify your desired target with the timestamp information (via POST Request). A webhook for a submitted hash is triggered as soon as the tamper-proof timestamp with the selected crypto currency has been created. 
     * @param {String} authorization A valid API key is essential for authorization to handle the request.
     * @param {module:model/TimestampBulkRequest} timestampBulkRequest DTO for the bulk hash submission. Add all relevant information concerning your hash submissions.
     * @param {module:api/BulkApi~createBulkTimestampCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/DefaultOfTimestampResponse>}
     */
    this.createBulkTimestamp = function(authorization, timestampBulkRequest, callback) {
      var postBody = timestampBulkRequest;

      // verify the required parameter 'authorization' is set
      if (authorization === undefined || authorization === null) {
        throw new Error("Missing the required parameter 'authorization' when calling createBulkTimestamp");
      }

      // verify the required parameter 'timestampBulkRequest' is set
      if (timestampBulkRequest === undefined || timestampBulkRequest === null) {
        throw new Error("Missing the required parameter 'timestampBulkRequest' when calling createBulkTimestamp");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Authorization': authorization
      };
      var formParams = {
      };

      var authNames = ['API Key Authorization'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [DefaultOfTimestampResponse];

      return this.apiClient.callApi(
        '/v4/timestamp/bulk/create', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getSeedStatus operation.
     * @callback module:api/BulkApi~getSeedStatusCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DefaultOfTimestampData} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Seed Status
     * With this interface you can request the status for a certain seed. This is used when checking the status of previously submitted hashes and avoids sending individual status requests for each hash.
     * @param {String} authorization A valid API key is essential for authorization to handle the request.
     * @param {String} seedId ID of the timestamp seed
     * @param {module:api/BulkApi~getSeedStatusCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DefaultOfTimestampData}
     */
    this.getSeedStatus = function(authorization, seedId, callback) {
      var postBody = null;

      // verify the required parameter 'authorization' is set
      if (authorization === undefined || authorization === null) {
        throw new Error("Missing the required parameter 'authorization' when calling getSeedStatus");
      }

      // verify the required parameter 'seedId' is set
      if (seedId === undefined || seedId === null) {
        throw new Error("Missing the required parameter 'seedId' when calling getSeedStatus");
      }


      var pathParams = {
        'seed_id': seedId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Authorization': authorization
      };
      var formParams = {
      };

      var authNames = ['API Key Authorization'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = DefaultOfTimestampData;

      return this.apiClient.callApi(
        '/v4/timestamp/status/seed/{seed_id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
