
/*
 * OriginStamp Client
 *
 * OpenAPI spec version: 3.0
 * OriginStamp Documentation: https://docs.originstamp.com
 * Contact: mail@originstamp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CurrencyModel', 'model/DefaultOfDownloadLinkResponse', 'model/DefaultOfListOfCurrencyModel', 'model/DefaultOfTimestampData', 'model/DefaultOfTimestampResponse', 'model/DefaultOfVoid', 'model/DefaultOfWebhookResponse', 'model/DefaultOfstring', 'model/DefaultUsageResponse', 'model/DownloadLinkResponse', 'model/ManualWebhookRequest', 'model/Notification', 'model/ProofRequest', 'model/TimestampBulkRequest', 'model/TimestampData', 'model/TimestampRequest', 'model/TimestampResponse', 'model/UsageResponse', 'model/WebhookRequest', 'model/WebhookResponse', 'api/APIKeyApi', 'api/BulkApi', 'api/ProofApi', 'api/SchedulerApi', 'api/TimestampApi', 'api/WebhookApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/CurrencyModel'), require('./model/DefaultOfDownloadLinkResponse'), require('./model/DefaultOfListOfCurrencyModel'), require('./model/DefaultOfTimestampData'), require('./model/DefaultOfTimestampResponse'), require('./model/DefaultOfVoid'), require('./model/DefaultOfWebhookResponse'), require('./model/DefaultOfstring'), require('./model/DefaultUsageResponse'), require('./model/DownloadLinkResponse'), require('./model/ManualWebhookRequest'), require('./model/Notification'), require('./model/ProofRequest'), require('./model/TimestampBulkRequest'), require('./model/TimestampData'), require('./model/TimestampRequest'), require('./model/TimestampResponse'), require('./model/UsageResponse'), require('./model/WebhookRequest'), require('./model/WebhookResponse'), require('./api/APIKeyApi'), require('./api/BulkApi'), require('./api/ProofApi'), require('./api/SchedulerApi'), require('./api/TimestampApi'), require('./api/WebhookApi'));
  }
}(function(ApiClient, CurrencyModel, DefaultOfDownloadLinkResponse, DefaultOfListOfCurrencyModel, DefaultOfTimestampData, DefaultOfTimestampResponse, DefaultOfVoid, DefaultOfWebhookResponse, DefaultOfstring, DefaultUsageResponse, DownloadLinkResponse, ManualWebhookRequest, Notification, ProofRequest, TimestampBulkRequest, TimestampData, TimestampRequest, TimestampResponse, UsageResponse, WebhookRequest, WebhookResponse, APIKeyApi, BulkApi, ProofApi, SchedulerApi, TimestampApi, WebhookApi) {
  'use strict';

  /**
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var OriginStamp = require('index'); // See note below*.
   * var xxxSvc = new OriginStamp.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new OriginStamp.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new OriginStamp.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new OriginStamp.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 3.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The CurrencyModel model constructor.
     * @property {module:model/CurrencyModel}
     */
    CurrencyModel: CurrencyModel,
    /**
     * The DefaultOfDownloadLinkResponse model constructor.
     * @property {module:model/DefaultOfDownloadLinkResponse}
     */
    DefaultOfDownloadLinkResponse: DefaultOfDownloadLinkResponse,
    /**
     * The DefaultOfListOfCurrencyModel model constructor.
     * @property {module:model/DefaultOfListOfCurrencyModel}
     */
    DefaultOfListOfCurrencyModel: DefaultOfListOfCurrencyModel,
    /**
     * The DefaultOfTimestampData model constructor.
     * @property {module:model/DefaultOfTimestampData}
     */
    DefaultOfTimestampData: DefaultOfTimestampData,
    /**
     * The DefaultOfTimestampResponse model constructor.
     * @property {module:model/DefaultOfTimestampResponse}
     */
    DefaultOfTimestampResponse: DefaultOfTimestampResponse,
    /**
     * The DefaultOfVoid model constructor.
     * @property {module:model/DefaultOfVoid}
     */
    DefaultOfVoid: DefaultOfVoid,
    /**
     * The DefaultOfWebhookResponse model constructor.
     * @property {module:model/DefaultOfWebhookResponse}
     */
    DefaultOfWebhookResponse: DefaultOfWebhookResponse,
    /**
     * The DefaultOfstring model constructor.
     * @property {module:model/DefaultOfstring}
     */
    DefaultOfstring: DefaultOfstring,
    /**
     * The DefaultUsageResponse model constructor.
     * @property {module:model/DefaultUsageResponse}
     */
    DefaultUsageResponse: DefaultUsageResponse,
    /**
     * The DownloadLinkResponse model constructor.
     * @property {module:model/DownloadLinkResponse}
     */
    DownloadLinkResponse: DownloadLinkResponse,
    /**
     * The ManualWebhookRequest model constructor.
     * @property {module:model/ManualWebhookRequest}
     */
    ManualWebhookRequest: ManualWebhookRequest,
    /**
     * The Notification model constructor.
     * @property {module:model/Notification}
     */
    Notification: Notification,
    /**
     * The ProofRequest model constructor.
     * @property {module:model/ProofRequest}
     */
    ProofRequest: ProofRequest,
    /**
     * The TimestampBulkRequest model constructor.
     * @property {module:model/TimestampBulkRequest}
     */
    TimestampBulkRequest: TimestampBulkRequest,
    /**
     * The TimestampData model constructor.
     * @property {module:model/TimestampData}
     */
    TimestampData: TimestampData,
    /**
     * The TimestampRequest model constructor.
     * @property {module:model/TimestampRequest}
     */
    TimestampRequest: TimestampRequest,
    /**
     * The TimestampResponse model constructor.
     * @property {module:model/TimestampResponse}
     */
    TimestampResponse: TimestampResponse,
    /**
     * The UsageResponse model constructor.
     * @property {module:model/UsageResponse}
     */
    UsageResponse: UsageResponse,
    /**
     * The WebhookRequest model constructor.
     * @property {module:model/WebhookRequest}
     */
    WebhookRequest: WebhookRequest,
    /**
     * The WebhookResponse model constructor.
     * @property {module:model/WebhookResponse}
     */
    WebhookResponse: WebhookResponse,
    /**
     * The APIKeyApi service constructor.
     * @property {module:api/APIKeyApi}
     */
    APIKeyApi: APIKeyApi,
    /**
     * The BulkApi service constructor.
     * @property {module:api/BulkApi}
     */
    BulkApi: BulkApi,
    /**
     * The ProofApi service constructor.
     * @property {module:api/ProofApi}
     */
    ProofApi: ProofApi,
    /**
     * The SchedulerApi service constructor.
     * @property {module:api/SchedulerApi}
     */
    SchedulerApi: SchedulerApi,
    /**
     * The TimestampApi service constructor.
     * @property {module:api/TimestampApi}
     */
    TimestampApi: TimestampApi,
    /**
     * The WebhookApi service constructor.
     * @property {module:api/WebhookApi}
     */
    WebhookApi: WebhookApi
  };

  return exports;
}));
